language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt59-meta-full
  - source /opt/qt59/bin/qt59-env.sh

script:
  - /opt/qt59/bin/qmake
  - make

# For gitter 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c791f10b1abf61b68f2a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
